name: first workflow

env:
  WORKFLOW_VAR: "This variable is declared at tge workflow level"

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! THis is the first job
      - name: checkout the repository
        uses: actions/checkout@v4.1.1
      - name: greet a user with the hello world function
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Paul'
      - name: the greeting time
        run: |
          echo "The time of the greeting was s: ${{ steps.greetings.outputs.time }}"
          
        

  secondJob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: "This is a job variable"
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is the second job
          echo and this is a multi-line script
      - name: environment variables
        env:
          STEP_VAR: "This variable is declared at the step level"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "The following is a secret: ${{ secrets.SOME_SECRET }}, of course, I cant tell you because then it woulsnt be a secret..."
          echo "The following are default environment variables:"
          echo $GITHUB_ACTOR
          echo $GITHUB_JOB
          echo $GITHUB_REF
